import { BigInt, BigDecimal, Address } from '@graphprotocol/graph-ts';

export let BIGINT_ZERO = BigInt.fromI32(0);
export let BIGINT_ONE = BigInt.fromI32(1);
export let BIGDECIMAL_ZERO = BigDecimal.fromString('0');
export let BIGDECIMAL_ONE = BigDecimal.fromString('1');
export let ADDRESS_ZERO = Address.fromString(
  '0x0000000000000000000000000000000000000000'
);
export let ADDRESS_DAI = Address.fromString(
  '0x6b175474e89094c44da98b954eedeac495271d0f'
);

export let ORDER_TYPE_PRIORITY = new Array<string>(18);

ORDER_TYPE_PRIORITY[0] = 'NONE';
ORDER_TYPE_PRIORITY[1] = 'MINT';
ORDER_TYPE_PRIORITY[2] = 'EXERCISE';
ORDER_TYPE_PRIORITY[3] = 'REDEEM';
ORDER_TYPE_PRIORITY[4] = 'CLOSE';
ORDER_TYPE_PRIORITY[5] = 'UNWIND';
ORDER_TYPE_PRIORITY[6] = 'NEUTRAL';
ORDER_TYPE_PRIORITY[7] = 'NEW_MARKET';
ORDER_TYPE_PRIORITY[8] = 'APPROVE';
ORDER_TYPE_PRIORITY[9] = 'LONG';
ORDER_TYPE_PRIORITY[10] = 'SHORT';
ORDER_TYPE_PRIORITY[11] = 'WRITE';
ORDER_TYPE_PRIORITY[12] = 'CLOSE_LONG';
ORDER_TYPE_PRIORITY[13] = 'CLOSE_SHORT';
ORDER_TYPE_PRIORITY[14] = 'ADD_LIQUIDITY_CUSTOM'; // Uniswap Swap event
ORDER_TYPE_PRIORITY[15] = 'ADD_LIQUIDITY';
ORDER_TYPE_PRIORITY[16] = 'REMOVE_LIQUIDITY_CUSTOM'; // Uniswap Swap event
ORDER_TYPE_PRIORITY[17] = 'REMOVE_LIQUIDITY_CLOSE';
